"""Generate complete static bilingual pages. No browser framework or build dependency."""
from pathlib import Path
import json, html, re, os, tomllib
from urllib.parse import quote
from datetime import date

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'dist'
DATA = json.loads((ROOT / 'src/content.json').read_text(encoding='utf-8'))
SERVICES = DATA['services']
OFFICES = DATA['offices']
JOBS = DATA['jobs']
ARTICLES = DATA['articles']
BASE = (os.environ.get('SITE_URL') or os.environ.get('URL') or DATA['siteUrl']).rstrip('/')
ROUTES = {
 'home':['',''], 'about':['entreprise','company'], 'sectors':['secteurs','sectors'],
 'international':['presence-internationale','international-presence'], 'references':['references','references'],
 'careers':['carrieres','careers'], 'application':['candidature','apply'], 'events':['evenements-rh','hr-events'],
 'news':['actualites','insights'], 'contact':['contact','contact'], 'quote':['demande-de-devis','request-a-quote'],
 'legal':['mentions-legales','legal-notice'], 'privacy':['confidentialite','privacy'], 'cookies':['cookies','cookies'],
 'success':['merci','thank-you'], '404':['404','404']
}
TITLES = {
 'home':['Le partenaire RH des industries d’Afrique Centrale','The HR partner for Central Africa’s industries'],
 'about':['L’entreprise','Our company'], 'sectors':['Secteurs d’intervention','Industries we serve'],
 'international':['Ancrage africain. Connexions internationales.','African roots. International connections.'],
 'references':['Ils nous font confiance','Client references'], 'careers':['Votre prochaine étape professionnelle','Your next career move'],
 'application':['Faites connaître votre talent','Tell us about your skills'], 'events':['Événements RH','HR events'],
 'news':['Regards sur les métiers et les ressources humaines','Perspectives on people and industry'],
 'contact':['Parlons de votre projet','Let’s talk about your project'], 'quote':['Construisons la réponse à votre besoin','Let’s define the support you need'],
 'legal':['Mentions légales','Legal notice'], 'privacy':['Protection des données et des candidatures','Privacy and candidate data'],
 'cookies':['Politique cookies','Cookie policy'], 'success':['Votre demande a été reçue','Your submission has been received'],
 '404':['Cette page n’est pas disponible','This page is not available']
}
INTROS = {
 'about':['L’ingénierie et les solutions RH au service des entreprises en République du Congo et en Afrique Centrale.','Engineering and HR solutions for businesses in the Republic of Congo and Central Africa.'],
 'sectors':['Comprendre vos métiers pour répondre à vos besoins en compétences.','Understanding your industry to respond to your workforce needs.'],
 'international':['Depuis Pointe-Noire, un réseau ouvert sur les marchés africains, Londres et les partenaires techniques d’Aberdeen.','From Pointe-Noire, connections across African markets, a London commercial hub and technical partners in Aberdeen.'],
 'references':['Un espace réservé aux références dont la publication sera validée par l’entreprise.','A dedicated space for references approved for publication by the company.'],
 'careers':['Métiers techniques, opérations offshore, fonctions RH et administratives : explorez le parcours candidat.','Technical roles, offshore operations, HR and administrative work: explore the candidate journey.'],
 'application':['Présentez votre parcours pour une candidature spontanée.','Share your background through a speculative application.'],
 'events':['Forums emploi, rencontres professionnelles et sessions de formation.','Employment forums, professional meetings and training sessions.'],
 'news':['Des sujets à explorer pour les entreprises et les candidats.','Topics to explore for businesses and candidates.'],
 'contact':['Un besoin en personnel, une formation ou un projet d’implantation : contactez le bureau adapté.','Staffing, training or a market-entry project: contact the appropriate office.'],
 'quote':['Présentez votre contexte en quatre étapes. Votre demande servira de base à un échange avec SAS Congo.','Tell us about your requirements in four steps. Your request will provide a starting point for a discussion with SAS Congo.']
}
CONTRACTS={'cdi':['CDI','Permanent'],'cdd':['CDD','Fixed term'],'freelance':['Freelance','Freelance'],'fulltime':['Temps plein','Full time'],'parttime':['Temps partiel','Part time'],'internship':['Stage','Internship'],'temporary':['Temporaire','Temporary'],'offshore':['Mission offshore','Offshore assignment']}
SECTORS={'oil':['Pétrolier','Oil & Gas'],'services':['Parapétrolier','Oilfield services'],'industry':['Industriel','Industrial'],'maritime':['Maritime','Maritime']}
CATEGORIES={'law':['Droit du travail au Congo','Employment in Congo'],'recruitment':['Recrutement','Recruitment'],'oil':['Oil & Gas','Oil & Gas'],'company':['Vie de l’entreprise','Company news'],'candidates':['Conseils candidats','Candidate advice']}
ICONS={
 'hr':'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 5a3 3 0 0 1 0 6M18 15a5 5 0 0 1 3 5"/>',
 'training':'<path d="m2 9 10-5 10 5-10 5-10-5M5 11v6l7 4 7-4v-6M22 9v7"/>',
 'representation':'<path d="M4 8h16v13H4zM9 8V4h6v4M4 13h16M10 13v3h4v-3"/>',
 'technical':'<path d="m4 20 7-7M15 3a6 6 0 0 0-5 9l-7 7 2 2 7-7a6 6 0 0 0 9-5l-4 3-4-4z"/>',
 'sanitation':'<path d="M12 3s-7 8-7 12a7 7 0 0 0 14 0c0-4-7-12-7-12M8 16a4 4 0 0 0 4 3"/>',
 'globe':'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18M5 7h14M5 17h14"/>',
 'shield':'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6zM8 12l3 3 5-6"/>',
 'target':'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/><path d="m12 12 8-8M17 4h3v3"/>',
 'ship':'<path d="M6 11V5h12v6M10 5V2h4v3M2 14l10-4 10 4-4 7H6zM2 22q3-2 5 0t5 0t5 0t5 0"/>'
}
def esc(s): return html.escape(str(s),quote=True)
def tr(fr,en,l): return en if l else fr
def url(key,l): return '/'+('en' if l else 'fr')+'/'+ROUTES[key][l].strip('/')+('/' if ROUTES[key][l] else '')
def surl(s,l): return '/'+('en' if l else 'fr')+'/'+s['slug'][l]+'/'
def a(href,label,cls='text-link'): return f'<a class="{cls}" href="{esc(href)}">{esc(label)}</a>'
def ph(fr,en,l): return f'<p class="placeholder">[À COMPLÉTER : {esc(tr(fr,en,l))}]</p>'
def rich(text):
 if text.startswith('[À COMPLÉTER'): return f'<p class="placeholder">{esc(text)}</p>'
 return f'<p>{esc(text)}</p>'
def icon(name): return f'<span class="icon" aria-hidden="true"><svg viewBox="0 0 24 24">{ICONS.get(name,ICONS["hr"])}</svg></span>'
def section(body,cls='',id=''):return f'<section class="section {cls}"'+(f' id="{id}"' if id else '')+f'><div class="wrap">{body}</div></section>'
def head(eyebrow,title,text='',link=''):return f'<div class="section-head"><div><span class="eyebrow">{esc(eyebrow)}</span><h2>{esc(title)}</h2></div>'+ (f'<p>{esc(text)}</p>' if text else link)+'</div>'
def image(name,alt,cls='',eager=False):
 dimensions={'offshore':(1600,1200),'office':(1200,800),'team':(800,1200),'people':(1200,800),'industry':(1200,900),'maritime':(1200,800)}
 w,h=dimensions.get(name,(1200,800))
 return f'<img class="{cls}" src="/assets/img/{name}.webp" alt="{esc(alt)}" width="{w}" height="{h}" '+('fetchpriority="high"' if eager else 'loading="lazy"')+' decoding="async">'

def header(l,key,alternate):
 nav=[('home',tr('Accueil','Home',l)),('about',tr('L’entreprise','Company',l))]
 links=''.join(f'<a href="{url(k,l)}"'+(' aria-current="page"' if key==k else '')+f'>{esc(v)}</a>' for k,v in nav)
 mega=''.join(f'<a href="{surl(s,l)}"><strong>{esc(s["short"][l])}</strong><small>{esc(s["intro"][l])}</small></a>' for s in SERVICES)
 links+=f'<details class="mega"><summary>{tr("Solutions","Solutions",l)}</summary><div class="mega-panel">{mega}</div></details>'
 links+=''.join(f'<a href="{url(k,l)}"'+(' aria-current="page"' if key==k else '')+f'>{esc(v)}</a>' for k,v in [('sectors',tr('Secteurs','Industries',l)),('careers',tr('Carrières','Careers',l)),('news',tr('Actualités','Insights',l)),('contact','Contact')])
 links+=a(url('quote',l),tr('Demander un devis','Request a quote',l),'btn small')
 return f'''<a class="skip" href="#main">{tr('Aller au contenu','Skip to content',l)}</a>
 <div class="topbar"><div class="wrap"><a href="tel:+242057753232">+242 05 775 3232</a><a class="email" href="mailto:secretariat@sascongo.com">secretariat@sascongo.com</a><span class="region">Pointe-Noire · {tr('Afrique Centrale','Central Africa',l)}</span><div class="languages" aria-label="{tr('Langue','Language',l)}"><a href="{alternate if l else url_for_current}" lang="fr" hreflang="fr" {'aria-current="true"' if not l else ''}>FR</a><span aria-hidden="true">/</span><a href="{url_for_current if l else alternate}" lang="en" hreflang="en" {'aria-current="true"' if l else ''}>EN</a></div></div></div>
 <header class="site-header"><div class="wrap nav-row"><a class="brand" href="{url('home',l)}" aria-label="SAS Congo — {tr('Ingénierie & Solutions RH — Accueil','Engineering & HR Solutions — Home',l)}"><img src="/assets/img/logo.webp" width="77" height="65" alt="SAS Congo"><span class="brand-copy"><strong>{tr('Ingénierie','Engineering',l)}</strong>{tr('& Solutions RH','& HR Solutions',l)}</span></a><button class="menu-toggle" aria-controls="navigation" aria-expanded="false" aria-label="{tr('Ouvrir le menu','Open menu',l)}">☰</button><nav class="primary-nav" id="navigation" aria-label="{tr('Navigation principale','Main navigation',l)}">{links}</nav></div></header>'''

def consent(l,form=''):
 return f'<label class="check"><input type="checkbox" name="consent" value="yes" required><span>{tr("J’accepte que mes données soient utilisées pour traiter cette demande.","I agree to the use of my information to process this request.",l)} <a href="{url("privacy",l)}"><u>{tr("Protection des données","Privacy information",l)}</u></a>.</span></label>'
def field(name,label,l,type='text',required=False,options=None,autocomplete=None):
 id='f-'+name
 attr=f' id="{id}" name="{name}"'+(' required' if required else '')+(f' autocomplete="{autocomplete}"' if autocomplete else '')
 if options is not None:el=f'<select{attr}>'+''.join(f'<option value="{esc(v)}">{esc(s)}</option>' for v,s in options)+'</select>'
 elif type=='textarea':el=f'<textarea{attr} rows="5"></textarea>'
 else:el=f'<input{attr} type="{type}"'+(' accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document"' if type=='file' else '')+(' min="0" step="1"' if type=='number' else '')+'>'
 return f'<div class="field"><label for="{id}">{esc(label)}'+(' *' if required else '')+f'</label>{el}</div>'
def form_start(name,l,extra=''):
 return f'<form class="form-shell" name="{name}-{l}" method="POST" action="{url("success",l)}" data-success="{url("success",l)}" data-netlify="true" netlify-honeypot="bot-field" {extra}><input type="hidden" name="form-name" value="{name}-{l}"><div class="honeypot" aria-hidden="true"><label>{tr("Ne pas remplir","Leave empty",l)}<input name="bot-field" tabindex="-1" autocomplete="off"></label></div>'
def form_end(l,label=None):return consent(l)+f'<p class="form-help">{tr("Les champs marqués * sont obligatoires.","Fields marked * are required.",l)}</p><div class="actions"><button class="btn" type="submit">{esc(label or tr("Envoyer la demande","Send request",l))}</button></div><p class="form-status" role="status" aria-live="polite"></p></form>'

def footer(l):
 sols=''.join(f'<li>{a(surl(s,l),s["short"][l],"")}</li>' for s in SERVICES if s['id'] in ['hr','training','representation','technical','sanitation'])
 useful=''.join(f'<li>{a(url(k,l),v,"")}</li>' for k,v in [('about',tr('L’entreprise','Company',l)),('international',tr('Présence internationale','International presence',l)),('references',tr('Références','References',l)),('careers',tr('Carrières','Careers',l)),('events',tr('Événements RH','HR events',l)),('application',tr('Déposer un CV','Submit a CV',l))])
 legal=''.join(a(url(k,l),TITLES[k][l],'') for k in ['legal','privacy','cookies'])
 nl=form_start('newsletter',l)+field('email','E-mail',l,'email',True,autocomplete='email').replace('f-email','newsletter-email')+consent(l)+f'<button class="btn small" type="submit">{tr("S’inscrire","Subscribe",l)}</button><p class="form-status" role="status"></p></form>'
 return f'''<footer class="site-footer"><div class="wrap"><div class="footer-grid"><div><a class="footer-brand" href="{url('home',l)}"><img src="/assets/img/logo.webp" width="100" height="83" alt="SAS Congo"><strong>{tr('Ingénierie &<br>Solutions RH','Engineering &<br>HR Solutions',l)}</strong></a><p>{tr('Des solutions adaptées à votre activité, votre métier et votre environnement.','Solutions shaped around your business, industry and operating environment.',l)}</p>{ph('liens LinkedIn et Facebook officiels','official LinkedIn and Facebook links',l)}</div><div><h3>{tr('Nos solutions','Our solutions',l)}</h3><ul>{sols}</ul></div><div><h3>{tr('Liens utiles','Useful links',l)}</h3><ul>{useful}</ul></div><div><h3>{tr('Restons en contact','Stay in touch',l)}</h3><p>112 Avenue du Docteur Moé Poaty<br>Pointe-Noire, République du Congo</p><p><a href="tel:+242057753232">+242 05 775 3232</a><br><a href="mailto:secretariat@sascongo.com">secretariat@sascongo.com</a></p><a href="{url('contact',l)}">{tr('Tous nos bureaux →','All our offices →',l)}</a></div></div><details class="newsletter-panel"><summary>{tr('Recevoir nos actualités','Receive our updates',l)}</summary>{nl}</details><div class="footer-bottom"><span>© <span data-year>{date.today().year}</span> SAS Congo — {tr('Ingénierie & Solutions RH','Engineering & HR Solutions',l)}</span><div>{legal}<button type="button" class="text-link" data-cookie-settings>{tr('Préférences cookies','Cookie settings',l)}</button></div></div></div></footer>
 <aside class="cookie-banner" aria-label="{tr('Préférences cookies','Cookie preferences',l)}" hidden><h2>{tr('Votre confidentialité, votre choix.','Your privacy, your choice.',l)}</h2><p>{tr('Ce site n’utilise aucun outil de mesure d’audience. La carte Google Maps ne se charge qu’avec votre accord. Votre choix est enregistré sur cet appareil.','This site uses no analytics tools. Google Maps loads only with your permission. Your preference is stored on this device.',l)}</p><div class="actions"><button class="btn" data-cookie-choice="accept">{tr('Accepter la carte externe','Allow external map',l)}</button><button class="btn secondary" data-cookie-choice="reject">{tr('Refuser','Decline',l)}</button>{a(url('cookies',l),tr('En savoir plus','Learn more',l))}</div></aside>'''

def cta(l,service=None):
 target=url('quote',l)+(f'?service={service}' if service else '')
 return f'<section class="cta-band"><div class="wrap"><div><h2>{tr("Parlons de vos besoins en personnel.","Let’s talk about your workforce needs.",l)}</h2><p><a href="tel:+242057753232">+242 05 775 3232</a> · secretariat@sascongo.com</p></div><div class="actions">{a(target,tr("Demander un devis","Request a quote",l),"btn white")}</div></div></section>'
def page_hero(title,intro,l,oily=False,parent=None):
 bread=f'<a href="{url("home",l)}">{tr("Accueil","Home",l)}</a><span aria-hidden="true">/</span>'
 if parent:bread+=a(parent[0],parent[1],'')+'<span aria-hidden="true">/</span>'
 bread+=f'<span aria-current="page">{esc(title)}</span>'
 return f'<section class="page-hero {"oil" if oily else ""}"><div class="wrap"><nav class="breadcrumb" aria-label="{tr("Fil d’Ariane","Breadcrumb",l)}">{bread}</nav><span class="eyebrow">SAS Congo · {tr("Ingénierie & Solutions RH","Engineering & HR Solutions",l)}</span><h1>{esc(title)}</h1><p class="intro">{esc(intro)}</p></div></section>'
def service_cards(l,ids=None):
 services=[s for s in SERVICES if s['id'] in (ids or ['hr','training','representation','technical','sanitation'])]
 return '<div class="grid services-grid">'+''.join(f'<article class="card service-card reveal"><span class="card-number">SAS / {i+1:02d}</span>{icon(s["id"])}<h3>{esc(s["short"][l])}</h3><p>{esc(s["intro"][l])}</p>{a(surl(s,l),tr("Découvrir la solution","Explore this service",l))}</article>' for i,s in enumerate(services))+'</div>'
def job_cards(l,jobs=None):
 return ''.join(f'<article class="card job-card"><span class="badge">{tr("EXEMPLE · OFFRE FICTIVE","EXAMPLE · FICTIONAL VACANCY",l) if j["example"] else tr("OFFRE","VACANCY",l)}</span><h3>{esc(j["title"][l])}</h3><p>{esc(j["description"][l])}</p><div class="job-meta"><span>{esc(j["location"])}</span><span>{CONTRACTS[j["contract"]][l]}</span><span>{SECTORS[j["sector"]][l]}</span></div>{ph("date de publication d’une offre réelle","real vacancy publication date",l) if not j.get("publishedAt") else f"<time datetime='{esc(j['publishedAt'])}'>{esc(j['publishedAt'])}</time>"}{a(url("careers",l)+j["id"]+"/",tr("Voir la fiche","View details",l))}</article>' for j in (jobs or JOBS))
def article_cards(l,articles=None):
 return ''.join(f'<article class="card article-card" data-category="{art["category"]}">{image("offshore" if art["category"]=="oil" else "office",tr("Visuel d’illustration du sujet","Illustrative photograph",l),"article-cover")}<div><span class="badge">{tr("IDÉE ÉDITORIALE · À VALIDER","EDITORIAL IDEA · FOR APPROVAL",l) if not art["published"] else tr("ARTICLE","ARTICLE",l)}</span><span class="eyebrow">{CATEGORIES[art["category"]][l]}</span><h3>{esc(art["title"][l])}</h3>{a(url("news",l)+art["id"]+"/",tr("Consulter le modèle","View the template",l) if not art["published"] else tr("Lire l’article","Read article",l))}</div></article>' for art in (articles or ARTICLES))
def office_detail(o,l,cls=''):
 name=o['name'] if not l else o['name'].replace('(siège)','(headquarters)').replace('(Londres)','(London)').replace('Sénégal','Senegal')
 person=o['person'] if not l else o['person'].replace('Secrétariat','Secretariat')
 phones=' / '.join(f'<a href="tel:{re.sub(r"[^+0-9]","",p)}">{p}</a>' for p in o['phones'])
 address=o.get('address') or tr('[À COMPLÉTER : adresse du bureau de ','[À COMPLÉTER : office address for ',l)+o['city']+']'
 return f'<div class="{cls}"><span class="country">{esc(o["country"][l])}</span><h3>{esc(name)}</h3><p class="contact-name">{esc(person)}</p><p>{esc(address)}</p><p>{phones}<br><a href="mailto:{esc(o["email"])}">{esc(o["email"])}</a></p>'+ (rich(o['note'][l]) if o.get('note') else '')+'</div>'
def international_map(l):
 points=''.join(f'<circle class="map-dot" cx="{o["x"]}" cy="{o["y"]}" r="7"/><text class="map-city" x="{o["x"]+12}" y="{o["y"]+4}">{o["city"]}</text><circle class="map-button" cx="{o["x"]}" cy="{o["y"]}" r="18" role="button" tabindex="0" aria-label="{esc(o["city"])}" data-map-office="{i}"/>' for i,o in enumerate(OFFICES))
 svg=f'<svg viewBox="0 0 750 550" role="group" aria-label="{tr("Carte schématique des bureaux SAS","Schematic map of SAS offices",l)}"><path class="map-land" d="M213 172 261 126 353 110 425 128 490 151 529 205 591 223 614 283 589 316 552 350 531 406 489 475 464 516 425 475 395 413 387 342 340 301 285 295 240 270 212 236 184 215Z"/><path class="map-land" d="M611 380 627 360 641 390 622 433 609 438Z"/><path class="map-land" d="M391 34 407 22 424 35 418 55 403 64 389 53Z"/><path class="map-route" d="M410 50Q240 100 195 225M410 50Q555 170 465 325M195 225Q320 340 465 325M465 325L448 390M465 325Q565 280 550 150"/>{points}<circle class="map-dot" cx="550" cy="150" r="4"/><text class="map-city" x="570" y="155">Aberdeen*</text></svg>'
 tabs=''.join(f'<button type="button" data-office="{i}" aria-pressed="{str(i==0).lower()}" aria-controls="office-panel-{i}">{o["city"]}</button>' for i,o in enumerate(OFFICES))
 panels=''.join(f'<div id="office-panel-{i}" data-office-panel="{i}" {"hidden" if i else ""}>{office_detail(o,l,"office-preview")}</div>' for i,o in enumerate(OFFICES))
 return f'<div class="split"><div class="map-panel">{svg}<p class="map-note">{tr("Carte schématique, sans échelle. * Aberdeen : partenaires techniques, pas un bureau SAS.","Schematic map, not to scale. * Aberdeen: technical partners, not a SAS office.",l)}</p></div><div><span class="eyebrow">{tr("Notre réseau","Our network",l)}</span><h2>{tr("Une présence locale.<br>Une ouverture internationale.","Local presence.<br>International reach.",l)}</h2><div class="office-tabs" aria-label="{tr("Choisir un bureau","Select an office",l)}">{tabs}</div>{panels}</div></div>'

def home(l):
 hero=f'''<section class="hero">{image('offshore',tr('Plateforme offshore en mer — photo d’illustration, hors site SAS Congo','Offshore platform at sea — illustrative photo, not a SAS Congo site',l),'hero-image',True)}<div class="wrap"><span class="eyebrow">{tr('Expertise locale. Perspective internationale.','Local knowledge. International perspective.',l)}</span><h1>{tr('Le partenaire RH<br>des industries<br><em>d’Afrique Centrale.</em>','The HR partner<br>for the industries<br><em>of Central Africa.</em>',l)}</h1><p>{tr('Ingénierie, recrutement et solutions RH pour les secteurs pétrolier, parapétrolier, industriel et maritime. À terre comme en mer, avançons avec les bonnes compétences.','Engineering, recruitment and HR solutions for oil, oilfield services, industrial and maritime businesses. Onshore and offshore, move forward with the right skills.',l)}</p><div class="actions">{a(url('quote',l),tr('Demander un devis','Request a quote',l),'btn')}{a(url('application',l),tr('Déposer mon CV','Submit my CV',l),'btn ghost')}</div><p class="hero-caption">{tr('Photo d’illustration · À remplacer par un visuel de l’entreprise','Illustrative photo · Replace with a company photograph',l)}</p><div class="hero-foot"><span>Pointe-Noire / {tr('République du Congo','Republic of Congo',l)}</span><span>Onshore & Offshore</span><span>{tr('L’humain au cœur de vos opérations','People at the heart of your operations',l)} ↓</span></div></div></section>'''
 paths=f'<div class="pathbar"><div class="wrap paths"><a class="path" href="{url("quote",l)}">{icon("representation")}<div><b>{tr("Vous êtes une entreprise","For businesses",l)}</b><small>{tr("Construisons votre solution RH","Let’s shape your HR solution",l)}</small></div><span aria-hidden="true">↗</span></a><a class="path" href="{url("careers",l)}">{icon("hr")}<div><b>{tr("Vous êtes candidat","For candidates",l)}</b><small>{tr("Donnons une nouvelle direction à votre parcours","Explore your next career move",l)}</small></div><span aria-hidden="true">↗</span></a></div></div>'
 stats=[('années d’expérience validées','validated years of experience','Expérience','Experience'),('nombre de collaborateurs placés','number of people placed','Collaborateurs placés','People placed'),('nombre d’entreprises clientes','number of client companies','Entreprises clientes','Client companies'),('nombre de pays de présence validé','validated number of countries','Présence internationale','International presence')]
 stathtml='<div class="stats"><div class="wrap stats-grid">'+''.join(f'<div class="stat"><strong>{tr(label,enlabel,l)}</strong>{ph(fr,en,l)}</div>' for fr,en,label,enlabel in stats)+'</div></div>'
 solutions=section(head(tr('Nos solutions','Our solutions',l),tr('Les bonnes compétences.<br>Le bon accompagnement.','The right skills.<br>The right support.',l).replace('<br>',' '),tr('Cinq pôles d’activité pour relier vos enjeux humains, techniques et commerciaux.','Five business areas connecting your people, technical and commercial needs.',l))+service_cards(l))
 reasons=[('globe','Ancrage local, réseau international','Local roots, international connections','Une base à Pointe-Noire, un hub commercial à Londres et un réseau africain.','A Pointe-Noire base, a London commercial hub and an African network.'),('technical','Expertise Oil & Gas','Oil & Gas expertise','Des prestations RH et techniques reliées aux besoins de l’industrie.','HR and technical services connected to industry needs.'),('ship','Personnel onshore et offshore','Onshore and offshore personnel','Un recrutement adapté aux métiers et aux environnements d’intervention.','Recruitment tailored to roles and operating environments.'),('shield','Appui en droit social','Employment law support','Un accompagnement tenant compte du contexte juridique de votre demande.','Support informed by the legal context of your request.'),('training','Partenaires à Aberdeen','Aberdeen-based partners','Un lien technique pour les formations et l’assistance Oil & Gas.','Technical connections for training and Oil & Gas support.'),('hr','Coordination de vos besoins','Coordinating your requirements','Une offre qui réunit recrutement, gestion RH et accompagnement opérationnel.','An offer spanning recruitment, HR management and operational support.')]
 reasonhtml=''.join(f'<div class="reason">{icon(i)}<div><h3>{esc(tr(fr,en,l))}</h3><p>{esc(tr(p,q,l))}</p></div></div>' for i,fr,en,p,q in reasons)
 why=section(f'<div class="split"><div><span class="eyebrow">{tr("Pourquoi SAS Congo","Why SAS Congo",l)}</span><h2>{tr("Comprendre votre terrain.<br>Accompagner vos équipes.","Understand your environment.<br>Support your people.",l)}</h2><p>{tr("SAS Congo apporte des réponses adaptées à votre activité, votre métier et votre environnement, grâce à son ancrage local et à son expertise technique.","SAS Congo responds to your business, industry and operating environment through local knowledge and technical expertise.",l)}</p>{a(url("about",l),tr("Découvrir l’entreprise","Meet SAS Congo",l))}<div class="editorial-image" style="margin-top:35px">{image("people",tr("Réunion professionnelle — photo d’illustration, hors équipe SAS Congo","Professional meeting — illustrative photo, not the SAS Congo team",l))}<div class="image-note"><strong>{tr("L’humain au cœur des métiers","People at the heart of industry",l)}</strong>{tr("Photo d’illustration · À remplacer par une photo SAS Congo","Illustrative photo · Replace with a SAS Congo photograph",l)}</div></div></div><div>{reasonhtml}</div></div>','paper')
 sectors=section(head(tr('Vos métiers','Your industry',l),tr('L’expertise au contact du terrain.','Expertise connected to operations.',l))+sector_tiles(l))
 steps=[('Analyse du besoin','Understand the need','Définir le poste et son environnement.','Define the role and its environment.'),('Sourcing','Source talent','Identifier les profils dans le réseau.','Identify profiles through the network.'),('Sélection','Select candidates','Examiner les critères du poste.','Review the role requirements.'),('Mise à disposition','Mobilise personnel','Convenir des modalités de mobilisation.','Agree mobilisation arrangements.'),('Suivi & gestion RH','Follow-up & HR','Organiser le suivi et la gestion administrative.','Organise follow-up and administration.')]
 method=section(head(tr('Notre méthode','Our approach',l),tr('Un besoin clair. Un parcours structuré.','A clear brief. A structured process.',l))+'<div class="steps">'+''.join(f'<article class="step"><h3>{tr(fr,en,l)}</h3><p>{tr(p,q,l)}</p></article>' for fr,en,p,q in steps)+'</div>','paper')
 network=section(international_map(l),'dark')
 trust=section(head(tr('Nos références','References',l),tr('Ils nous font confiance.','Relationships built on trust.',l),link=a(url('references',l),tr('Voir cet espace','View this space',l)))+ph('liste validée des clients et autorisation d’affichage des logos','approved client list and permission to display logos',l)+'<div class="logo-track">'+''.join(f'<div class="logo-slot">{ph("logo client autorisé", "approved client logo",l)}</div>' for _ in range(4))+'</div>')
 careers=section(head(tr('Espace candidats','For candidates',l),tr('Votre talent. De nouvelles perspectives.','Your skills. New possibilities.',l),link=a(url('careers',l),tr('Explorer les offres','Explore vacancies',l)))+rich(tr('Les fiches ci-dessous sont des exemples fictifs de présentation. Elles ne correspondent à aucun poste ouvert.','The cards below are fictional presentation examples. They are not open vacancies.',l))+'<div class="grid three">'+job_cards(l)+'</div>','paper')
 news=section(head(tr('Actualités & idées','Insights & ideas',l),tr('Les sujets qui nous rapprochent.','Topics that connect us.',l),link=a(url('news',l),tr('Toutes les actualités','All insights',l)))+'<div class="grid three">'+article_cards(l,ARTICLES[:3])+'</div>')
 return hero+paths+stathtml+solutions+why+sectors+method+network+trust+careers+news+cta(l)

def sector_tiles(l):
 visuals={'oil':'offshore','services':'industry','industry':'industry','maritime':'maritime'}
 return '<div class="grid four">'+''.join(f'<a class="sector-card" href="{url("sectors",l)}#{k}">{image(visuals[k],tr("Visuel d’illustration du secteur ","Illustrative industry photo: ",l)+names[l])}<div><h3>{names[l]}</h3><span>{tr("Découvrir le secteur","Explore this industry",l)} <b aria-hidden="true">↗</b></span></div></a>' for k,names in SECTORS.items())+'</div>'

def about(l):
 content=page_hero(TITLES['about'][l],INTROS['about'][l],l)
 content+=section(f'<div class="split"><div class="editorial-image">{image("office",tr("Bureaux professionnels — illustration à remplacer par les locaux SAS Congo","Professional offices — replace with SAS Congo premises",l))}<div class="image-note"><strong>Pointe-Noire</strong>{tr("Un ancrage en République du Congo","Based in the Republic of Congo",l)}</div></div><div><span class="eyebrow">{tr("Notre ancrage","Our roots",l)}</span><h2>{tr("Des solutions RH au plus près de vos métiers.","HR solutions close to your industry.",l)}</h2><p>{tr("SAS Congo – Ingénierie & Solutions RH est spécialisée en ingénierie et en solutions ressources humaines en République du Congo et dans la sous-région Afrique Centrale.","SAS Congo – Engineering & HR Solutions specialises in engineering and human resources solutions in the Republic of Congo and the Central African region.",l)}</p><p>{tr("L’entreprise accompagne les secteurs pétrolier, parapétrolier, industriel, maritime et d’autres activités, avec des réponses adaptées à chaque environnement.","The company supports oil, oilfield services, industrial, maritime and other businesses with solutions suited to their operating context.",l)}</p>{ph("historique et année de création à confirmer ; une source tierce indique 2008","company history and founding year to confirm; a third-party source mentions 2008",l)}</div></div>')
 cards=[('Mission','Mission',tr('Apporter des réponses adaptées à l’activité, au métier et à l’environnement de chaque client.','Provide solutions suited to each client’s business, industry and environment.',l)),('Vision proposée','Proposed vision',tr('Accompagner le développement des industries africaines par les compétences et une gestion RH structurée.','Support African industries through skills and structured HR management.',l)),('Valeurs proposées','Proposed values',tr('Fiabilité, réactivité, conformité, sécurité et proximité.','Reliability, responsiveness, compliance, safety and proximity.',l))]
 content+=section(head(tr('Ce qui nous guide','What guides us',l),tr('Une mission concrète. Des repères à partager.','A practical purpose. Shared principles.',l))+'<div class="grid three">'+''.join(f'<article class="card"><h3>{tr(fr,en,l)}</h3><p>{esc(text)}</p>'+(ph('vision et valeurs proposées à valider par la direction','proposed vision and values to be approved by management',l) if i else '')+'</article>' for i,(fr,en,text) in enumerate(cards))+'</div>','paper')
 content+=section(head(tr('Direction','Leadership',l),tr('Le mot du Directeur Général','A message from the Managing Director',l))+ph('texte, nom, fonction et photo du Directeur Général','Managing Director message, name, role and photo',l)+head(tr('Notre équipe','Our team',l),tr('L’équipe dirigeante','Leadership team',l))+'<div class="grid three">'+''.join(f'<article class="card">{ph("photo, nom et fonction d’un membre de l’équipe dirigeante","leadership team member photo, name and role",l)}</article>' for _ in range(3))+'</div>')
 commitments=[('HSE & sécurité','HSE & safety','politique HSE, engagements de sécurité et certifications éventuelles','HSE policy, safety commitments and any certifications'),('Éthique & conformité','Ethics & compliance','charte éthique, dispositifs de conformité et responsabilités','ethics policy, compliance procedures and responsibilities'),('Non-discrimination','Non-discrimination','politique de recrutement équitable et engagements de non-discrimination','fair recruitment policy and non-discrimination commitments')]
 content+=section(head(tr('Engagements','Commitments',l),tr('Des engagements à documenter.','Commitments to document.',l))+'<div class="grid three">'+''.join(f'<article class="card">{icon("shield")}<h3>{tr(fr,en,l)}</h3>{ph(p,q,l)}</article>' for fr,en,p,q in commitments)+'</div>','paper')
 content+=section(head(tr('Le groupe SAS','The SAS group',l),tr('Une perspective au-delà des frontières.','A perspective beyond borders.',l))+rich(tr('Le groupe réunit le hub commercial de Londres, SAS International Group Ltd., et les implantations au Sénégal, en Côte d’Ivoire et en Angola. Le savoir-faire se déploie vers d’autres pays pétroliers africains.','The group connects the London commercial hub, SAS International Group Ltd., with locations in Senegal, Côte d’Ivoire and Angola. Its expertise is extending to other African oil-producing countries.',l))+a(url('international',l),tr('Explorer notre présence internationale','Explore our international presence',l)))
 return content+cta(l)

def faq_data(s,l):
 return [
 (tr('Comment définir le périmètre de la mission ?','How is the engagement scope defined?',l),tr('Un échange permet de préciser votre contexte, vos objectifs et les prestations attendues. Le périmètre est convenu avant l’intervention.','A discussion establishes your context, objectives and required services. The scope is agreed before work begins.',l)),
 (tr('Quels sont les délais et les tarifs ?','What are the timings and fees?',l),tr('Ils dépendent du besoin, de la disponibilité des compétences et du périmètre retenu. Une proposition est préparée après l’étude de votre demande.','They depend on the requirements, availability of skills and agreed scope. A proposal is prepared after your request is reviewed.',l)),
 (tr('Quelles informations transmettre pour un devis ?','What information is needed for a quote?',l),tr('Précisez le service recherché, les profils ou objectifs, le lieu, le calendrier souhaité et les coordonnées de votre entreprise.','Provide the service required, roles or objectives, location, preferred schedule and company contact details.',l)),
 (tr('Peut-on associer plusieurs prestations ?','Can several services be combined?',l),tr('Les besoins peuvent être étudiés ensemble. Les prestations retenues et leurs modalités restent à définir avec SAS Congo.','Requirements can be considered together. The selected services and arrangements must be agreed with SAS Congo.',l)),
 (tr('Comment sont traitées les exigences spécifiques du site ?','How are site-specific requirements handled?',l),tr('Les exigences du poste, du site et de votre organisation doivent être partagées lors du cadrage. Les qualifications et documents nécessaires sont examinés selon la mission.','Share role, site and organisational requirements when defining the brief. Qualifications and documentation are reviewed for the specific assignment.',l))]
def service(s,l):
 body=page_hero(s['title'][l],s['intro'][l],l,s['id'] in ['staffing','technical','training','representation'],(surl(SERVICES[0],l),SERVICES[0]['short'][l]) if s['id'] in ['staffing','recruitment','audit','tools','director','law','coaching'] else None)
 body+=section(f'<div class="split"><div><span class="eyebrow">{tr("Votre besoin","Your requirement",l)}</span><h2>{tr("Le besoin auquel nous répondons","The need we address",l)}</h2>{rich(s["need"][l])}</div><div><span class="eyebrow">{tr("Notre réponse","Our response",l)}</span><h2>{tr("Un accompagnement adapté à votre contexte","Support suited to your context",l)}</h2>{rich(s["response"][l])}</div></div>')
 body+=section(head(tr('Votre entreprise','Your business',l),tr('Ce que vous obtenez','What you receive',l))+'<div class="grid three">'+''.join(f'<article class="card">{icon("target")}<h3>{esc(v)}</h3></article>' for v in s['benefits'][l])+'</div>','paper')
 steps= [('Cadrer','Define','Préciser vos objectifs et vos contraintes.','Clarify objectives and constraints.'),('Préparer','Prepare','Définir le périmètre et les moyens.','Agree the scope and resources.'),('Intervenir','Deliver','Mettre en œuvre la prestation convenue.','Carry out the agreed service.'),('Suivre','Review','Faire le point sur la mission et ses suites.','Review the engagement and next steps.')]
 if s['id']=='representation':steps=[('Organiser la visite','Plan the visit','Planifier les visites de prospection ou de finalisation d’accords au Congo.','Plan prospecting visits or visits to finalise agreements in Congo.'),('Prospecter','Explore','Développer les réseaux commerciaux et rechercher des projets d’investissement en infrastructures ou matières premières.','Develop commercial networks and seek investment projects in infrastructure or raw materials.'),('Identifier','Identify','Identifier les clients potentiels et les interlocuteurs pertinents.','Identify potential clients and relevant contacts.'),('Négocier','Negotiate','Accompagner la négociation des termes et conditions des contrats dans l’intérêt du client.','Support negotiation of contract terms and conditions in the client’s interests.')]
 body+=section(head(tr('Déroulé proposé','Proposed process',l),tr('Comment ça se passe','How it works',l))+'<div class="steps four">'+''.join(f'<article class="step"><h3>{tr(fr,en,l)}</h3><p>{tr(p,q,l)}</p></article>' for fr,en,p,q in steps)+'</div>'+ph('modalités opérationnelles et livrables de ce service à valider','operational arrangements and deliverables for this service to approve',l))
 body+=section(f'<div class="body-copy"><span class="eyebrow">{tr("Pour qui","Who it is for",l)}</span><h2>{tr("Les entreprises concernées","Businesses we support",l)}</h2>{rich(s["audience"][l])}</div>','paper')
 if s['id']=='hr':body+=section(head(tr('Nos expertises RH','Our HR expertise',l),tr('Une solution pour chaque enjeu RH.','Support for each HR requirement.',l))+service_cards(l,['staffing','recruitment','audit','tools','director','law','coaching']))
 if s['id']=='training':
  body+=section(head(tr('Catalogue','Training catalogue',l),tr('Des programmes à préciser avec vous.','Programmes to define with you.',l))+'<div class="grid two">'+''.join(f'<article class="card">{icon("training")}<h3>{tr(fr,en,l)}</h3>{ph("intitulés, durées, public, prérequis et certifications des formations","course titles, duration, audience, prerequisites and certifications",l)}</article>' for fr,en in [('Formations RH','HR training'),('Formations Oil & Gas','Oil & Gas training')])+'</div>'+form_start('training',l)+'<h2>'+tr('Demander une formation intra-entreprise','Request in-company training',l)+'</h2><div class="form-grid">'+field('company',tr('Société','Company',l),l,required=True)+field('name',tr('Nom','Name',l),l,required=True)+field('email','E-mail',l,'email',True)+field('phone',tr('Téléphone','Phone',l),l,'tel')+field('participants',tr('Nombre de participants','Number of participants',l),l,'number')+field('location',tr('Lieu souhaité','Preferred location',l),l)+field('topic',tr('Sujet et objectifs','Topic and objectives',l),l,'textarea',True)+'</div>'+form_end(l),'paper')
 if s['id']=='representation':
  body+=section(head(tr('Un bureau clé en main','A turnkey office',l),tr('Un relais commercial, administratif et opérationnel.','Commercial, administrative and operational support.',l))+'<ul class="list">'+''.join(f'<li>{tr(fr,en,l)}</li>' for fr,en in [('Animation et développement des réseaux commerciaux','Commercial network development'),('Assistance administrative et lobbying auprès des administrations et gouvernements','Administrative support and liaison with public authorities'),('Suivi des opérations de sous-traitance','Subcontracting follow-up'),('Recherche de projets porteurs d’investissement','Identification of investment project opportunities')])+'</ul>'+rich(tr('Une formule modulable, avec la présence d’un partenaire local et les fonctions d’une filiale sans en porter le management ni les charges fixes. SAS Congo facilite les liens bilatéraux entre entreprises européennes, américaines, asiatiques et africaines.','A flexible arrangement providing a local partner and the functions of a subsidiary without its management burden or fixed overheads. SAS Congo facilitates bilateral business relationships between European, American, Asian and African companies.',l))+rich(tr('Zones couvertes : République du Congo et Afrique subsaharienne, selon le périmètre de la mission.','Coverage: the Republic of Congo and sub-Saharan Africa, depending on the engagement scope.',l))+a(url('contact',l)+'?subject=representation',tr('Planifier un échange','Arrange a conversation',l),'btn')+ph('outil de prise de rendez-vous et disponibilités validées','approved scheduling tool and availability',l),'paper')
 faq=faq_data(s,l)
 if s['id']=='sanitation':faq=[(tr('Quelles prestations sont disponibles ?','Which services are available?',l),tr('Le détail de ce pôle d’activité n’a pas encore été fourni. Contactez SAS Congo pour préciser votre besoin.','Details of this business area have not yet been supplied. Contact SAS Congo to discuss your needs.',l))]+faq[:3]
 body+=section(head(tr('Questions fréquentes','Frequently asked questions',l),tr('Les premiers repères pour votre projet.','A starting point for your project.',l))+'<div class="faq">'+''.join(f'<details><summary>{esc(q)}</summary><p>{esc(r)}</p></details>' for q,r in faq)+'</div>')
 body+=section(f'<div class="split"><div><h2>{tr("Parlons de ce service.","Let’s discuss this service.",l)}</h2>{a(url("quote",l)+"?service="+s["id"],tr("Demander un devis pour ce service","Request a quote for this service",l),"btn")}</div><div><h3>{tr("Services complémentaires","Related services",l)}</h3><ul class="list">'+''.join(f'<li>{a(surl(r,l),r["short"][l])}</li>' for r in SERVICES if r['id'] in (['hr','training','technical'] if s['id']!='hr' else ['training','representation','technical']) and r['id']!=s['id'])+'</ul></div></div>','paper')
 return body,faq

def sectors(l):
 body=page_hero(TITLES['sectors'][l],INTROS['sectors'][l],l)+section(sector_tiles(l))
 profiles={'oil':[['Opérateurs','Techniciens de maintenance','HSE','Logistique','Administratifs'],['Operators','Maintenance technicians','HSE roles','Logistics staff','Administrative staff']], 'services':[['Techniciens','Ingénieurs','Superviseurs','Logistique'],['Technicians','Engineers','Supervisors','Logistics staff']], 'industry':[['Production','Maintenance','Qualité','Ressources humaines'],['Production roles','Maintenance','Quality roles','Human resources']], 'maritime':[['Opérations portuaires','Coordination logistique','Maintenance','Administration'],['Port operations','Logistics coordination','Maintenance','Administration']]}
 for i,(k,names) in enumerate(SECTORS.items()):body+=section(f'<div class="split"><div><span class="eyebrow">{tr("Secteur","Industry",l)} / {i+1:02d}</span><h2>{names[l]}</h2><p>{tr("SAS Congo intervient auprès des entreprises de ce secteur avec des solutions RH et un accompagnement adapté au besoin exprimé.","SAS Congo supports businesses in this industry through HR solutions and support tailored to the stated need.",l)}</p>{a(surl(SERVICES[0],l),tr("Explorer les solutions RH","Explore HR solutions",l))}</div><div><h3>{tr("Exemples de familles de postes","Examples of role families",l)}</h3><p class="form-help">{tr("Exemples indicatifs ; aucune référence à des missions réalisées ou à des postes ouverts.","Illustrative examples; these do not represent completed assignments or open vacancies.",l)}</p><ul class="list">'+''.join(f'<li>{p}</li>' for p in profiles[k][l])+'</ul></div></div>','paper' if i%2==0 else '',k)
 return body+cta(l)
def international(l):
 body=page_hero(TITLES['international'][l],INTROS['international'][l],l)+section(international_map(l),'dark')
 body+=section(head(tr('Nos bureaux','Our offices',l),tr('Les coordonnées de votre interlocuteur.','Contact the relevant office.',l))+'<div class="grid offices">'+''.join(f'<article class="card">{office_detail(o,l,"office-card")}</article>' for o in OFFICES)+'</div>')
 body+=section(head(tr('Développement','Expansion',l),tr('Le savoir-faire SAS vers d’autres marchés.','SAS expertise across further markets.',l))+rich(tr('Pays en cours de développement : Mauritanie, Gabon et Namibie. Le Sénégal, la Côte d’Ivoire et l’Angola font également partie du déploiement vers les pays pétroliers africains.','Markets under development: Mauritania, Gabon and Namibia. Senegal, Côte d’Ivoire and Angola are also part of the expansion into African oil-producing countries.',l))+ph('statut, périmètre et coordonnées des développements en Mauritanie, au Gabon et en Namibie','status, scope and contact details for developments in Mauritania, Gabon and Namibia',l)+rich(tr('Aberdeen, Royaume-Uni : partenaires techniques pour les formations et l’assistance Oil & Gas. Londres : hub commercial SAS International Group Ltd.','Aberdeen, United Kingdom: technical partners for Oil & Gas training and support. London: the SAS International Group Ltd. commercial hub.',l)),'paper')
 return body+cta(l)
def references(l):
 return page_hero(TITLES['references'][l],INTROS['references'][l],l)+section(ph('liste validée des clients et autorisation d’affichage des logos ; Newpark, Aksa, Bourbon et SGMP sont uniquement des noms identifiés sur l’ancien site, à confirmer','approved client list and logo display permission; Newpark, Aksa, Bourbon and SGMP were only identified on the former site and require confirmation',l)+'<div class="logo-track">'+''.join(f'<div class="logo-slot">{ph("logo client validé","approved client logo",l)}</div>' for _ in range(4))+'</div>')+section(head(tr('Retours d’expérience','Client feedback',l),tr('Des témoignages à recueillir.','Testimonials to collect.',l))+'<div class="grid three">'+''.join(f'<article class="card"><h3>{tr("Emplacement témoignage","Testimonial placeholder",l)}</h3>{ph("citation authentique, auteur, fonction, entreprise et autorisation de publication","authentic quote, author, role, company and publication permission",l)}</article>' for _ in range(3))+'</div>','paper')+cta(l)

def careers(l):
 filt=f'<form class="filters" data-job-filters><div class="form-grid">'+field('keywords',tr('Mots-clés','Keywords',l),l,'search')+field('location',tr('Localisation','Location',l),l,options=[('',tr('Tous les lieux','All locations',l))]+[(loc,loc) for loc in sorted(set(j['location'] for j in JOBS))])+field('sector',tr('Secteur','Industry',l),l,options=[('',tr('Tous les secteurs','All industries',l))]+[(k,v[l]) for k,v in SECTORS.items()])+field('contract',tr('Contrat','Contract',l),l,options=[('',tr('Tous les contrats','All contracts',l))]+[(k,v[l]) for k,v in CONTRACTS.items()])+f'</div><label class="check"><input type="checkbox" name="remote" value="yes">{tr("Télétravail","Remote work",l)}</label><div class="actions"><button class="btn small" type="submit">{tr("Rechercher","Search",l)}</button><button class="btn secondary small" type="reset">{tr("Réinitialiser","Reset",l)}</button></div></form>'
 body=page_hero(TITLES['careers'][l],INTROS['careers'][l],l)+section(rich(tr('Démonstration : les trois offres sont fictives et marquées EXEMPLE. Aucune candidature ne peut être adressée à ces offres.','Demonstration: all three vacancies are fictional and marked EXAMPLE. Applications cannot be made to these vacancies.',l))+filt+f'<p class="result-count" data-job-count role="status">{tr("3 offres de démonstration","3 demonstration vacancies",l)}</p><div class="grid three" data-job-list>'+job_cards(l)+'</div><noscript><p>'+tr('Les filtres nécessitent JavaScript. Toutes les offres sont affichées.','Filters require JavaScript. All vacancies are displayed.',l)+'</p></noscript>')
 body+=section(f'<div class="split"><div><span class="eyebrow">{tr("Candidature spontanée","Speculative applications",l)}</span><h2>{tr("Votre parcours mérite d’être connu.","Let us get to know your experience.",l)}</h2><p>{tr("Présentez vos compétences, votre expérience et les métiers qui vous intéressent.","Share your skills, experience and the roles that interest you.",l)}</p>{a(url("application",l),tr("Déposer mon CV","Submit my CV",l),"btn")}</div><div><h3>{tr("Préparer sa candidature","Preparing your application",l)}</h3><ul class="list"><li>{tr("Présentez les expériences pertinentes pour le poste.","Highlight experience relevant to the role.",l)}</li><li>{tr("Vérifiez vos coordonnées et la lisibilité du CV.","Check your contact details and CV readability.",l)}</li><li>{tr("Indiquez uniquement les certifications que vous détenez.","Only list certifications you hold.",l)}</li></ul>{ph("à valider par l’entreprise : SAS Congo ne demande jamais d’argent pour un recrutement","company to validate: SAS Congo never charges candidates for recruitment",l)}</div></div>','paper')
 return body
def job_page(j,l):
 body=page_hero(j['title'][l],j['description'][l],l,parent=(url('careers',l),tr('Carrières','Careers',l)))
 body+=section(f'<div class="split"><div><span class="badge">{tr("EXEMPLE — AUCUN POSTE OUVERT","EXAMPLE — NOT AN OPEN VACANCY",l) if j["example"] else tr("OFFRE","VACANCY",l)}</span><h2>{tr("Description et missions","Description and responsibilities",l)}</h2>{rich(j["description"][l])}<ul class="list">'+''.join(f'<li>{esc(v)}</li>' for v in j['missions'][l])+f'</ul><h2>{tr("Profil recherché","Candidate profile",l)}</h2>{rich(j["profile"][l])}<h2>{tr("Avantages et conditions","Benefits and conditions",l)}</h2>{ph("avantages, rémunération, durée, conditions et critères d’une offre réelle","benefits, remuneration, duration, conditions and requirements for a real vacancy",l)}</div><aside class="card"><h3>{tr("Repères du poste","Role details",l)}</h3><p>{esc(j["location"])}<br>{CONTRACTS[j["contract"]][l]}<br>{SECTORS[j["sector"]][l]}</p>{ph("date de publication et date de clôture d’une offre réelle","publication and closing dates for a real vacancy",l)}'+(f'<button class="btn" type="button" disabled>{tr("Postuler — exemple indisponible","Apply — unavailable example",l)}</button><p class="form-help">'+tr('Pour présenter votre parcours, utilisez la candidature spontanée.','To share your experience, use the speculative application form.',l)+'</p>'+a(url('application',l),tr('Candidature spontanée','Speculative application',l)) if j['example'] else a(url('application',l)+'?position='+quote(j['title'][l]),tr('Postuler','Apply',l),'btn'))+'</aside></div>')
 return body
def application(l):
 labels=[('last_name','Nom','Last name','text',True,'family-name'),('first_name','Prénom','First name','text',True,'given-name'),('phone','Téléphone','Phone','tel',True,'tel'),('email','E-mail','E-mail','email',True,'email'),('city','Ville','City','text',True,'address-level2'),('country','Pays','Country','text',True,'country-name'),('position','Poste visé','Role sought','text',True,None),('experience','Années d’expérience','Years of experience','number',True,None)]
 form=form_start('application',l,'enctype="multipart/form-data"')+f'<h2>{tr("Votre candidature","Your application",l)}</h2><div class="form-grid">'+''.join(field(n,tr(fr,en,l),l,typ,req,autocomplete=aut) for n,fr,en,typ,req,aut in labels)+'</div>'
 form+=f'<fieldset style="margin-top:25px"><legend>{tr("Certifications (facultatif)","Certifications (optional)",l)}</legend><div class="choice-grid">'+''.join(f'<label class="check"><input type="checkbox" name="certifications" value="{cert}">{cert}</label>' for cert in ['BOSIET','HUET','H2S'])+'</div></fieldset>'+field('other_certifications',tr('Autres certifications','Other certifications',l),l)+field('cv',tr('Votre CV — PDF ou DOCX, 5 Mo maximum','Your CV — PDF or DOCX, maximum 5 MB',l),l,'file',True)+field('cover_letter',tr('Lettre de motivation (facultative)','Cover letter (optional)',l),l,'textarea')+ph('durée de conservation des CV, base légale, responsable du traitement et procédure d’exercice des droits','CV retention period, legal basis, data controller and rights request procedure',l)+form_end(l,tr('Envoyer ma candidature','Submit my application',l))
 return page_hero(TITLES['application'][l],INTROS['application'][l],l)+section(f'<div class="split" style="align-items:start"><div><span class="eyebrow">{tr("Espace candidats","For candidates",l)}</span><h2>{tr("Des informations utiles, un dossier clair.","Useful information. A clear application.",l)}</h2><p>{tr("Déposez un CV à jour et précisez le poste ou le domaine visé. Les certifications sont facultatives et doivent correspondre à votre parcours réel.","Upload an up-to-date CV and specify the role or field you are seeking. Certification information is optional and should reflect your actual qualifications.",l)}</p><p>{tr("Le dépôt d’un dossier ne constitue ni une offre d’emploi ni un engagement de recrutement.","Submitting an application is not a job offer or a commitment to recruit.",l)}</p>{a(url("privacy",l),tr("Protection de vos données","Your data and privacy",l))}</div><div>{form}</div></div>')

def contact_form(l):
 f=form_start('contact',l)+f'<h2>{tr("Écrivez-nous","Send us a message",l)}</h2><div class="form-grid">'
 for n,fr,en,typ,req in [('name','Nom','Name','text',True),('company','Société','Company','text',False),('role','Fonction','Role','text',False),('email','E-mail','E-mail','email',True),('phone','Téléphone','Phone','tel',False),('country','Pays','Country','text',True)]:f+=field(n,tr(fr,en,l),l,typ,req)
 f+=field('subject',tr('Objet','Subject',l),l,required=True,options=[('hr',tr('Solutions RH','HR solutions',l)),('training',tr('Formation','Training',l)),('representation',tr('Représentation','Representation',l)),('application',tr('Candidature','Application',l)),('other',tr('Autre','Other',l))])+field('message',tr('Message','Message',l),l,'textarea',True)+'</div>'+form_end(l)
 return f
def contact(l):
 return page_hero(TITLES['contact'][l],INTROS['contact'][l],l)+section(f'<div class="split" style="align-items:start"><div><span class="eyebrow">{tr("Notre siège","Headquarters",l)}</span><h2>Pointe-Noire</h2>{office_detail(OFFICES[0],l,"office-card")}{ph("horaires d’ouverture du secrétariat","secretariat opening hours",l)}<div class="map-embed"><h3>{tr("Nous trouver","Find us",l)}</h3><p class="form-help">{tr("Emplacement approximatif : -4.7999, 11.8489. La carte est fournie par Google et nécessite votre accord.","Approximate location: -4.7999, 11.8489. The map is provided by Google and requires your permission.",l)}</p><button class="btn secondary" data-load-map>{tr("Autoriser Google Maps et afficher la carte","Allow Google Maps and show map",l)}</button></div></div><div>{contact_form(l)}</div></div>')+section(head(tr('Autres bureaux','Other offices',l),tr('Des interlocuteurs au-delà du Congo.','Contacts beyond Congo.',l))+'<div class="grid two">'+''.join(f'<article class="card">{office_detail(o,l,"office-card")}</article>' for o in OFFICES[1:])+'</div>','paper')+f'<aside class="whatsapp-placeholder">WhatsApp Business<br>{tr("[À COMPLÉTER : numéro WhatsApp Business]","[À COMPLÉTER : WhatsApp Business number]",l)}</aside>'
def quote_form(l):
 f=form_start('quote',l,'data-quote-form')+f'<div class="progress-label"><span data-step-label>{tr("Étape 1 sur 4","Step 1 of 4",l)}</span><span>{tr("Votre projet","Your project",l)}</span></div><progress max="4" value="1" aria-label="{tr("Progression de la demande","Request progress",l)}"></progress>'
 f+=f'<fieldset data-step><legend tabindex="-1">1. {tr("Quel est votre besoin ?","What do you need?",l)}</legend><p class="form-help">{tr("Sélectionnez une ou plusieurs solutions.","Select one or more services.",l)}</p><div class="choice-grid">'+''.join(f'<label class="choice"><input type="checkbox" name="services" value="{s["id"]}">{icon(s["id"])}<span>{esc(s["short"][l])}</span></label>' for s in SERVICES)+'</div></fieldset>'
 f+=f'<fieldset data-step><legend tabindex="-1">2. {tr("Précisez votre projet","Tell us about your project",l)}</legend><div class="form-grid">'+field('people',tr('Nombre de personnes','Headcount',l),l,'number')+field('profiles',tr('Profils ou objectifs','Roles or objectives',l),l,required=True)+field('environment',tr('Environnement','Environment',l),l,options=[('unspecified',tr('À préciser','To be defined',l)),('onshore','Onshore'),('offshore','Offshore'),('both',tr('Onshore et offshore','Onshore and offshore',l)),('na',tr('Non applicable','Not applicable',l))])+field('duration',tr('Durée envisagée','Expected duration',l),l)+field('start',tr('Date de démarrage souhaitée','Preferred start date',l),l,'date')+field('location',tr('Lieu d’intervention','Service location',l),l,required=True)+'</div></fieldset>'
 f+=f'<fieldset data-step><legend tabindex="-1">3. {tr("Votre entreprise","Your company",l)}</legend><div class="form-grid">'+''.join(field(n,tr(fr,en,l),l,typ,req) for n,fr,en,typ,req in [('company','Société','Company','text',True),('name','Nom du contact','Contact name','text',True),('role','Fonction','Role','text',True),('email','E-mail professionnel','Business email','email',True),('phone','Téléphone','Phone','tel',True),('country','Pays','Country','text',True)])+'</div></fieldset>'
 f+=f'<fieldset data-step><legend tabindex="-1">4. {tr("Récapitulatif et envoi","Review and submit",l)}</legend><dl class="recap" data-recap></dl><noscript><p>{tr("Vérifiez les champs renseignés ci-dessus avant l’envoi.","Review the fields above before submitting.",l)}</p></noscript>{consent(l)}</fieldset><div class="actions"><button class="btn secondary" type="button" data-back hidden>{tr("Retour","Back",l)}</button><button class="btn" type="button" data-next hidden>{tr("Continuer","Continue",l)}</button><button class="btn" type="submit">{tr("Envoyer ma demande","Submit my request",l)}</button></div><p class="form-status" role="status" aria-live="polite"></p></form>'
 return f
def quote_page(l):return page_hero(TITLES['quote'][l],INTROS['quote'][l],l)+section(f'<div class="split" style="align-items:start"><div><span class="eyebrow">{tr("Demande de devis","Request a quote",l)}</span><h2>{tr("Un point de départ pour votre projet.","A starting point for your project.",l)}</h2><p>{tr("Sélectionnez vos besoins et précisez votre contexte. La demande n’engage pas votre entreprise et ne remplace pas une proposition commerciale.","Select the services you need and describe your context. This request creates no commitment for your company and does not replace a commercial proposal.",l)}</p><p><a href="tel:+242057753232">+242 05 775 3232</a><br><a href="mailto:secretariat@sascongo.com">secretariat@sascongo.com</a></p></div><div>{quote_form(l)}</div></div>')

def news(l):
 filterhtml=field('category',tr('Catégorie','Category',l),l,options=[('',tr('Toutes les catégories','All categories',l))]+[(k,v[l]) for k,v in CATEGORIES.items()]).replace('<select','<select data-article-category')
 return page_hero(TITLES['news'][l],INTROS['news'][l],l)+section(rich(tr('Les six titres ci-dessous sont des propositions éditoriales SEO. Aucun article factuel ou juridique n’est publié sans validation.','The six titles below are proposed SEO editorial topics. No factual or legal article is published without approval.',l))+filterhtml+'<div class="grid three" style="margin-top:30px">'+article_cards(l)+'</div>')
def article_page(art,l):
 if art['published']:
  body=page_hero(art['title'][l],art.get('summary',['',''])[l],l,parent=(url('news',l),tr('Actualités','Insights',l)))
  content=f'<article class="article-layout"><div class="article-meta"><span>{esc(art.get("author",""))}</span><time datetime="{esc(art.get("publishedAt",""))}">{esc(art.get("publishedAt",""))}</time><span>{esc(art.get("readingTime",["",""])[l])}</span></div>'
  for part in art.get('sections',[]):
   content+=f'<h2>{esc(part["heading"][l])}</h2>'+''.join(rich(p) for p in part['paragraphs'][l])
  content+='</article>'
  return body+section(content)+section(head(tr('Articles liés','Related articles',l),tr('D’autres sujets à explorer.','More topics to explore.',l))+'<div class="grid three">'+article_cards(l,[x for x in ARTICLES if x['id']!=art['id']][:3])+'</div>','paper')
 body=page_hero(art['title'][l],tr('Modèle d’article — sujet proposé, contenu à rédiger et valider.','Article template — proposed topic, content to be written and approved.',l),l,parent=(url('news',l),tr('Actualités','Insights',l)))
 article=f'<article class="article-layout"><span class="badge">{tr("MODÈLE NON PUBLIÉ","UNPUBLISHED TEMPLATE",l)}</span><div class="article-meta"><span>{CATEGORIES[art["category"]][l]}</span><span>{tr("[À COMPLÉTER : date de publication]","[À COMPLÉTER : publication date]",l)}</span><span>{tr("[À COMPLÉTER : temps de lecture]","[À COMPLÉTER : reading time]",l)}</span></div>{ph("auteur et photo de l’article","article author and photo",l)}<h2>{tr("Introduction","Introduction",l)}</h2>{ph("introduction et angle éditorial validés","approved introduction and editorial angle",l)}<h2>{tr("Développement","Main discussion",l)}</h2>{ph("corps de l’article, sources vérifiables et validation juridique si nécessaire","article body, verifiable sources and legal review when required",l)}<h2>{tr("Repères pratiques","Practical guidance",l)}</h2>{ph("conseils validés et conclusion de l’article","approved guidance and article conclusion",l)}<div class="share"><span>{tr("Partager le sujet proposé","Share the proposed topic",l)}</span><a rel="noopener noreferrer" target="_blank" href="https://www.linkedin.com/sharing/share-offsite/?url={quote(BASE+url_for_current,safe="")}">LinkedIn ↗</a><a rel="noopener noreferrer" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u={quote(BASE+url_for_current,safe="")}">Facebook ↗</a><a href="mailto:?subject={quote(art["title"][l])}&amp;body={quote(BASE+url_for_current,safe="")}">E-mail ↗</a></div></article>'
 body+=section(article)+section(head(tr('Articles liés','Related articles',l),tr('D’autres sujets à explorer.','More topics to explore.',l))+'<div class="grid three">'+article_cards(l,[x for x in ARTICLES if x['id']!=art['id']][:3])+'</div>','paper')
 return body
def events(l):
 form=form_start('event-interest',l)+f'<h2>{tr("Être informé d’un événement","Express interest in an event",l)}</h2><div class="form-grid">'+field('name',tr('Nom','Name',l),l,required=True)+field('email','E-mail',l,'email',True)+field('event',tr('Événement ou thème souhaité','Event or topic of interest',l),l,required=True)+'</div>'+form_end(l)
 return page_hero(TITLES['events'][l],INTROS['events'][l],l)+section('<div class="grid three">'+''.join(f'<article class="card"><span class="badge">{tr("PROGRAMMATION À COMPLÉTER","PROGRAMME TO BE CONFIRMED",l)}</span><h2 style="font-size:23px">{tr(fr,en,l)}</h2>{ph("intitulé de l’événement, date, lieu, programme et modalités d’inscription","event title, date, location, programme and registration arrangements",l)}{a("#inscription",tr("Manifester mon intérêt","Express interest",l))}</article>' for fr,en in [('Forums emploi','Employment forums'),('Rencontres RH','HR meetings'),('Sessions de formation','Training sessions')])+'</div>')+section(form,'paper','inscription')
def legal_page(key,l):
 body=page_hero(TITLES[key][l],tr('Informations à compléter et à valider avant la mise en ligne publique.','Information to complete and approve before public launch.',l),l)
 if key=='legal':
  content='<h2>'+tr('Éditeur du site','Website publisher',l)+'</h2><p>SAS Congo – Ingénierie & Solutions RH<br>112 Avenue du Docteur Moé Poaty, Pointe-Noire, République du Congo<br>secretariat@sascongo.com · +242 05 775 3232</p>'+ph('raison sociale juridique, forme juridique, capital, immatriculation, identifiant fiscal et directeur de publication','legal entity name, legal form, capital, registration, tax identifier and publishing director',l)+'<h2>'+tr('Hébergement','Hosting',l)+'</h2>'+ph('identité, adresse et contact de l’hébergeur après déploiement Netlify','hosting provider identity, address and contact after Netlify deployment',l)+'<h2>'+tr('Propriété intellectuelle','Intellectual property',l)+'</h2>'+ph('droits sur les contenus, conditions de réutilisation et mentions obligatoires applicables','content rights, reuse terms and applicable mandatory notices',l)
 elif key=='privacy':
  content='<h2>'+tr('Les données des formulaires','Form information',l)+'</h2>'+rich(tr('Les formulaires demandent des coordonnées et les informations nécessaires à votre demande. La candidature permet de joindre un CV et de préciser votre expérience. Les champs requis sont identifiés.','Forms request contact details and information relevant to your request. The application form allows a CV upload and details of your experience. Required fields are identified.',l))+'<h2>'+tr('Finalités et traitement','Purposes and processing',l)+'</h2>'+rich(tr('Les demandes sont destinées à être traitées par SAS Congo. Le dispositif technique prévu est Netlify Forms. Aucun CV n’est conservé dans le navigateur ni ajouté au dépôt public du site.','Requests are intended for processing by SAS Congo. The planned technical service is Netlify Forms. CVs are not stored in the browser or added to the public website repository.',l))+ph('responsable du traitement, finalités précises, base légale, destinataires, sous-traitants et transferts internationaux éventuels','data controller, specific purposes, legal basis, recipients, processors and any international transfers',l)+'<h2>'+tr('Conservation des CV et autres données','Retention of CVs and other information',l)+'</h2>'+ph('durée de conservation des CV et candidatures, durée des demandes B2B et newsletter, modalités de suppression et mesures de sécurité','CV and application retention period, B2B and newsletter retention periods, deletion procedures and security measures',l)+'<h2>'+tr('Vos droits et votre interlocuteur','Your rights and contact',l)+'</h2>'+ph('droits applicables, procédure d’exercice, contact confidentialité ou DPO et autorité compétente','applicable rights, request procedure, privacy or DPO contact and competent authority',l)+rich(tr('Pour toute question sur les informations à fournir, contactez secretariat@sascongo.com.','For questions about information requested, contact secretariat@sascongo.com.',l))
 else:
  content='<h2>'+tr('Fonctionnement du site','How the site works',l)+'</h2>'+rich(tr('Aucun outil de mesure d’audience ni pixel publicitaire n’est installé. Les préférences de consentement sont enregistrées dans le stockage local de votre navigateur, sous la clé sas-cookie-consent.','No analytics tool or advertising pixel is installed. Consent preferences are saved in your browser’s local storage under the key sas-cookie-consent.',l))+'<h2>Google Maps</h2>'+rich(tr('La carte ne se charge pas avant un accord explicite. En autorisant son affichage, votre navigateur contacte Google. Vous pouvez refuser sans perdre l’accès aux coordonnées des bureaux.','The map does not load before explicit permission. When you allow it, your browser contacts Google. You can decline and still access office contact information.',l))+'<h2>'+tr('Polices de caractères','Fonts',l)+'</h2>'+rich(tr('Les polices Manrope et Inter sont hébergées avec le site. Leur affichage ne déclenche aucun appel à Google Fonts. Une police système prend le relais si nécessaire.','Manrope and Inter are hosted with the site. Displaying them does not contact Google Fonts. System fonts are used when needed.',l))+ph('inventaire définitif des traceurs de l’hébergeur, durées et validation de la politique cookies','final inventory of hosting provider trackers, durations and cookie policy approval',l)+'<button class="btn" type="button" data-cookie-settings>'+tr('Modifier mes préférences','Change my preferences',l)+'</button>'
 return body+section('<div class="body-copy">'+content+'</div>')

def metadata(title,description,l,path,alternate,extra=None,noindex=False):
 org={'@type':'Organization','@id':BASE+'/#organization','name':'SAS Congo – Ingénierie & Solutions RH','url':BASE,'logo':BASE+'/assets/img/logo.webp','email':'secretariat@sascongo.com','telephone':'+242 05 775 3232','areaServed':['Republic of Congo','Central Africa']}
 local={'@type':'LocalBusiness','@id':BASE+'/#headquarters','name':'SAS Congo','address':{'@type':'PostalAddress','streetAddress':'112 Avenue du Docteur Moé Poaty','addressLocality':'Pointe-Noire','addressCountry':'CG'},'telephone':'+242 05 775 3232','email':'secretariat@sascongo.com','parentOrganization':{'@id':BASE+'/#organization'}}
 bread={'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':tr('Accueil','Home',l),'item':BASE+url('home',l)}]}
 if path!=url('home',l):bread['itemListElement'].append({'@type':'ListItem','position':2,'name':title,'item':BASE+path})
 graph=[org,local,bread]+(extra or [])
 return f'''<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)}</title><meta name="description" content="{esc(description)}"><meta name="theme-color" content="#102c39">{('<meta name="robots" content="noindex,follow">' if noindex else '')}<link rel="canonical" href="{BASE+path}"><link rel="alternate" hreflang="{'en' if l else 'fr'}" href="{BASE+path}"><link rel="alternate" hreflang="{'fr' if l else 'en'}" href="{BASE+alternate}"><link rel="alternate" hreflang="x-default" href="{BASE+(alternate if l else path)}"><meta property="og:type" content="website"><meta property="og:title" content="{esc(title)}"><meta property="og:description" content="{esc(description)}"><meta property="og:url" content="{BASE+path}"><meta property="og:site_name" content="SAS Congo"><meta property="og:locale" content="{'en_GB' if l else 'fr_FR'}"><meta property="og:image" content="{BASE}/assets/img/offshore.webp"><meta property="og:image:alt" content="{tr('Plateforme offshore — illustration','Offshore platform — illustrative photograph',l)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{esc(title)}"><meta name="twitter:description" content="{esc(description)}"><meta name="twitter:image" content="{BASE}/assets/img/offshore.webp"><link rel="icon" type="image/png" href="/assets/img/favicon.png"><link rel="stylesheet" href="/assets/css/style.css"><script defer src="/assets/js/app.js"></script><script type="application/ld+json">{json.dumps({'@context':'https://schema.org','@graph':graph},ensure_ascii=False).replace('</','<\\/')}</script>'''

PAGES=[]
url_for_current=''
def write_page(key,l,path,alternate,body,title=None,description=None,extra=None,noindex=False):
 title=title or (TITLES[key][l]+' | SAS Congo')
 if len(title)>60:
  base_title=title.removesuffix(' | SAS Congo')
  title=base_title[:46].rsplit(' ',1)[0]+'… | SAS Congo'
 description=description or INTROS.get(key,[title+' — '+tr('Informations et contacts de SAS Congo.','SAS Congo information and contacts.',l)]*2)[l]
 if len(description)>155:description=description[:152].rsplit(' ',1)[0]+'…'
 document=f'<!doctype html><html lang="{"en" if l else "fr"}"><head>{metadata(title,description,l,path,alternate,extra,noindex)}</head><body class="page-{key}">{header(l,key,alternate)}<main id="main" tabindex="-1">{body}</main>{footer(l)}</body></html>'
 target=OUT / path.lstrip('/') / 'index.html'
 target.parent.mkdir(parents=True,exist_ok=True);target.write_text(document,encoding='utf-8')
 PAGES.append({'path':path,'alternate':alternate,'title':title,'description':description,'lang':'en' if l else 'fr','noindex':noindex})

def main():
 global url_for_current
 for l in [0,1]:
  for key,fn in [('home',home),('about',about),('sectors',sectors),('international',international),('references',references),('careers',careers),('application',application),('contact',contact),('quote',quote_page),('news',news),('events',events)]:
   url_for_current=url(key,l);body=fn(l)
   write_page(key,l,url_for_current,url(key,1-l),body,title=(tr('SAS Congo | RH, recrutement & Oil & Gas','SAS Congo | HR, staffing & Oil & Gas',l) if key=='home' else None))
  for s in SERVICES:
   url_for_current=surl(s,l);body,faq=service(s,l)
   extra=[{'@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':r}} for q,r in faq]}]
   write_page('service',l,url_for_current,surl(s,1-l),body,title=s['short'][l]+' | SAS Congo',description=s['intro'][l],extra=extra)
  for j in JOBS:
   url_for_current=url('careers',l)+j['id']+'/'
   extra=[]
   # Demonstration vacancies never receive JobPosting markup or indexation.
   if not j['example'] and j.get('publishedAt') and j.get('validThrough'):
    extra=[{'@type':'JobPosting','title':j['title'][l],'description':j['description'][l],'datePosted':j['publishedAt'],'validThrough':j['validThrough'],'hiringOrganization':{'@id':BASE+'/#organization'},'employmentType':j.get('schemaEmploymentType','CONTRACTOR'),'jobLocation':{'@type':'Place','address':{'@type':'PostalAddress','addressLocality':j['location'],'addressCountry':j.get('countryCode','CG')}}}]
   write_page('job',l,url_for_current,url('careers',1-l)+j['id']+'/',job_page(j,l),title=j['title'][l]+' | SAS Congo',description=j['title'][l]+' — '+j['description'][l],extra=extra,noindex=j['example'])
  for art in ARTICLES:
   url_for_current=url('news',l)+art['id']+'/'
   extra=[]
   if art['published'] and art.get('publishedAt') and art.get('author'):
    extra=[{'@type':'Article','headline':art['title'][l],'datePublished':art['publishedAt'],'author':{'@type':'Person','name':art['author']},'publisher':{'@id':BASE+'/#organization'},'mainEntityOfPage':BASE+url_for_current}]
   write_page('article',l,url_for_current,url('news',1-l)+art['id']+'/',article_page(art,l),title=art['title'][l]+' | SAS Congo',description=art['title'][l]+' — '+tr('Sujet proposé, modèle à compléter.','Proposed topic, template to complete.',l),extra=extra,noindex=not art['published'])
  for key in ['legal','privacy','cookies']:
   url_for_current=url(key,l);write_page(key,l,url_for_current,url(key,1-l),legal_page(key,l))
  for key in ['success','404']:
   url_for_current=url(key,l)
   text=tr('Votre envoi a été pris en compte. Vous pouvez revenir à l’accueil.','Your submission has been received. You can return to the home page.',l) if key=='success' else tr('Le lien a peut-être changé. Retrouvez nos solutions ou contactez le secrétariat.','The link may have changed. Explore our services or contact the secretariat.',l)
   write_page(key,l,url_for_current,url(key,1-l),page_hero(TITLES[key][l],text,l)+section(a(url('home',l),tr('Retour à l’accueil','Back to home',l),'btn')+' '+a(url('contact',l),tr('Contacter SAS Congo','Contact SAS Congo',l),'btn secondary')),noindex=True)
 (OUT/'404.html').write_text((OUT/'fr/404/index.html').read_text(encoding='utf-8'),encoding='utf-8')
 # Serve the complete French home at / as well as /fr/.
 (OUT/'index.html').write_text((OUT/'fr/index.html').read_text(encoding='utf-8'),encoding='utf-8')
 for asset in ['style.css','app.js']:
  text=(ROOT/'src'/asset).read_text(encoding='utf-8')
  if asset.endswith('.css'):text=(ROOT/'src/fonts.css').read_text(encoding='utf-8-sig')+'\n'+text
  if asset.endswith('.css'):text=re.sub(r'/\*.*?\*/','',text,flags=re.S);text=re.sub(r'\s+',' ',text)
  # JS is intentionally only whitespace-trimmed: preserve ASI and regex semantics.
  else:text='\n'.join(line.strip() for line in text.splitlines() if not line.strip().startswith('/*') and not line.strip().startswith('//'))
  folder='css' if asset.endswith('.css') else 'js';(OUT/'assets'/folder/asset).write_text(text,encoding='utf-8')
 (OUT/'assets/data/jobs.json').write_text(json.dumps(JOBS,ensure_ascii=False,separators=(',',':')),encoding='utf-8')
 (OUT/'assets/data/articles.json').write_text(json.dumps(ARTICLES,ensure_ascii=False,separators=(',',':')),encoding='utf-8')
 (OUT/'assets/data/pages.json').write_text(json.dumps(PAGES,ensure_ascii=False,indent=2),encoding='utf-8')
 sitemap=['<?xml version="1.0" encoding="UTF-8"?>','<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">']
 for p in PAGES:
  if p['noindex']:continue
  sitemap.append(f'<url><loc>{BASE+p["path"]}</loc><xhtml:link rel="alternate" hreflang="{p["lang"]}" href="{BASE+p["path"]}"/><xhtml:link rel="alternate" hreflang="{"fr" if p["lang"]=="en" else "en"}" href="{BASE+p["alternate"]}"/></url>')
 sitemap.append('</urlset>');(OUT/'sitemap.xml').write_text('\n'.join(sitemap),encoding='utf-8')
 (OUT/'robots.txt').write_text(f'User-agent: *\nAllow: /\nDisallow: /fr/merci/\nDisallow: /en/thank-you/\nSitemap: {BASE}/sitemap.xml\n',encoding='utf-8')
 # Mirror Netlify configuration for manual drag-and-drop ZIP deployments.
 config=tomllib.loads((ROOT/'netlify.toml').read_text(encoding='utf-8'))
 (OUT/'_redirects').write_text('\n'.join(f'{r["from"]} {r["to"]} {r["status"]}' for r in config.get('redirects',[]))+'\n',encoding='utf-8')
 header_lines=[]
 for rule in config.get('headers',[]):
  header_lines.append(rule['for'])
  header_lines.extend('  '+name+': '+value for name,value in rule['values'].items())
 (OUT/'_headers').write_text('\n'.join(header_lines)+'\n',encoding='utf-8')
 placeholders={}
 for path in OUT.rglob('*.html'):
  for text in re.findall(r'\[À COMPLÉTER\s*:\s*[^\]]+\]',path.read_text(encoding='utf-8')):
   text=html.unescape(text);placeholders.setdefault(text,set()).add('/'+path.relative_to(OUT).as_posix())
 for doc in ['README.md','ASSETS.md']:
  if not (ROOT/doc).exists():continue
  for text in re.findall(r'\[À COMPLÉTER\s*:\s*[^\]]+\]',(ROOT/doc).read_text(encoding='utf-8')):
   placeholders.setdefault(text,set()).add(doc)
 lines=['# Informations à fournir par SAS Congo','', 'Inventaire exhaustif extrait des pages générées (FR et EN).','']
 for text,paths in sorted(placeholders.items()):lines+=['- '+text,'  Pages : '+', '.join(sorted(paths)),'']
 (ROOT/'PLACEHOLDERS.md').write_text('\n'.join(lines),encoding='utf-8')
 print(f'Built {len(PAGES)} bilingual pages; {len(placeholders)} unique placeholders.')

if __name__=='__main__':main()
